language: ruby
gemfile: Gemfile.ci

# User container based travis infrastructure which allows caching
# features for open source projects.
sudo: false
cache: bundler

script:
- bundle exec publish-pageflow-theme-doc
